services:
  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password123
    command: --secure-file-priv=""
    volumes:
      - ./flag.txt:/flag.txt:ro
